reset:
    resource: "@resetBundle/Resources/config/routing.yml"
    prefix:   /reset

compte:
    resource: "@CompteBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check